import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { ImmutableXClient, Link } from '@imtbl/imx-sdk';
import { Wallet } from 'ethers';
import { AlchemyProvider, JsonRpcProvider } from '@ethersproject/providers';

interface UserInterface {
  address: string;
  starkPublicKey: string;
  ethNetwork: string;
  providerPreference: string;
}

const Home: NextPage = () => {
  const [client, setClient] = useState<ImmutableXClient>(Object);
  const [user, setUser] = useState<UserInterface>(Object);
  const [assets, setAssets] = useState(Object);

  const link = new Link(process.env.NEXT_APP_SANDBOX_LINK_URL);

  const linkSetup = async () => {
    const res = await link.setup({});
    setUser(res);
  };

  //not working without signer
  //needs a client initialized by -
  /**
   * signer
   * starkContractAddress
   * registrationContractAddress
   */
  const getUserProjects = async () => {
    const projects = await client.getProjects({});
    console.log(projects);
  };

  //possible with client initialized by apiAddress
  const getAllCollection = async () => {
    const tempCollections = await client.getCollections({});
    console.log(tempCollections);
  };

  const getUserAssets = async () => {
    const tempAssets = await client.getAssets({ user: user.address });
    setAssets(tempAssets.result);
    console.log(tempAssets);
  };

  //possible to know anyones balance
  const getBalance = async () => {
    const balance = await client.getBalance({
      user: '0x3a334A490Fdd7f1c8BB7e3e004dCb6832E05DE9c',
      tokenAddress: 'eth',
    });

    console.log(balance.balance.toString());
  };

  //question: how is marketplace connected with metamask
  //how is getting the signer for transaction
  //how is retrieveing data without signer

  //find a way to retrieve data without signer
  //while setting up the client
  //

  const setupClient = async () => {
    const imxApiUrl = 'https://api.sandbox.x.immutable.com/v1';
    console.log(imxApiUrl);
    const tempClient = await ImmutableXClient.build({
      publicApiUrl: imxApiUrl,
    });
    console.log(tempClient);
    setClient(tempClient);
  };

  useEffect(() => {
    setupClient();
  }, []);

  return (
    <div className="h-screen">
      <Head>
        <title>IMX Onboarding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full">
        <div className="flex justify-between">
          <button
            className="border-4 p-2 bg-blue-600 rounded-lg"
            onClick={linkSetup}
          >
            Link Wallet
          </button>
          <button
            className="border-4 p-2 bg-blue-600 rounded-lg"
            onClick={getBalance}
          >
            Get Balance
          </button>
          <button
            className="border-4 p-2 bg-blue-600 rounded-lg"
            onClick={getUserAssets}
          >
            Get Assets
          </button>
        </div>
        <div className="flex flex-col justify-center items-center border-teal-600">
          <p className="">{JSON.stringify(user, null, 2)}</p>
          <p className="">{JSON.stringify(assets, null, 2)}</p>
        </div>
      </main>
    </div>
  );
};

export default Home;
