import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { ImmutableXClient, Link } from '@imtbl/imx-sdk';
import { NEXT_APP_SANDBOX_LINK_URL } from '../config';
import { Signer } from 'ethers';
import CreateProject from '../components/CreateProject';
import { useadminClient } from '../hooks/useAdminClient';
import DeployContract from '../components/DeployContract';

const Home: NextPage = () => {
  const [client, setClient] = useState<ImmutableXClient>(Object);
  const [signer, setSigner] = useState<Signer>(Object);
  const [projects, setProjects] = useState(Array);
  const adminClient: ImmutableXClient | undefined = useadminClient();

  const link = new Link(NEXT_APP_SANDBOX_LINK_URL);

  const linkSetup = async () => {
    const res = await link.setup({});
  };

  const setupClient = async () => {};

  const getProjects = async () => {
    if (adminClient) {
      const res = await adminClient.getProjects();
      console.log(res);
      setProjects(res.result);
    }
  };

  useEffect(() => {
    if (adminClient) {
      console.log(adminClient);
      // getProjects();
    }
  }, [adminClient]);

  return (
    <div className="h-screen">
      <Head>
        <title>IMX Onboarding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full">
        <CreateProject />
        <DeployContract />
       
      </main>
    </div>
  );
};

export default Home;
