import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { ImmutableXClient, Link } from '@imtbl/imx-sdk';
import {  Wallet } from 'ethers';
import { AlchemyProvider, JsonRpcProvider } from '@ethersproject/providers';

interface UserInterface {
  address: string;
  starkPublicKey: string;
  ethNetwork: string;
  providerPreference: string;
}

const Home: NextPage = () => {
  const [client, setClient] = useState<ImmutableXClient>(Object);
  const [user, setUser] = useState<UserInterface>(Object);

  const link = new Link(process.env.NEXT_APP_SANDBOX_LINK_URL);

  const linkSetup = async () => {
    const res = await link.setup({});
    setUser(res);
  };

  const getUserProjects = async () => {
    const projects = await client.getProjects({});
    console.log(projects);
  };

  const getUserAssets = async () => {
    const assets = await client.getAssets({ user: user.address });
    console.log(assets);
  };

  //question: how is marketplace connected with metamask
  //how is getting the signer for transaction
  //how is retrieveing data without signer

  //find a way to retrieve data without signer
  //while setting up the client
  //

  const setupClient = async () => {
    const imxApiUrl = 'https://api.sandbox.x.immutable.com/v1';
    console.log(imxApiUrl);
    const provider = new AlchemyProvider(
      'goerli',
      'WmzAboIrYGOEDnuUJnxQ8ucuu3jfoR_q'
    );

    // const provider = new JsonRpcProvider(window.ethereum);
    
    // const signer = provider.getSigner();
    const signer = new Wallet(
      'f92e861a4b7771ee925922cd545874dcec0ad82cf87345eacff8ce47c23bb1b7'
    ).connect(provider);
    console.log(signer);
    const tempClient = await ImmutableXClient.build({
      publicApiUrl: imxApiUrl,
      starkContractAddress: '0x7917eDb51ecD6CdB3F9854c3cc593F33de10c623',
      registrationContractAddress: '0x1C97Ada273C9A52253f463042f29117090Cd7D83',
      // gasLimit: '7000000',
      // gasPrice: '40000000000',
      signer,
      // enableDebug: true,
    });
    const projects = await tempClient.getProjects();
    console.log(tempClient);
    console.log(projects);
    setClient(tempClient);
  };

  useEffect(() => {
    setupClient();
  }, []);

  return (
    <div className="h-screen">
      <Head>
        <title>IMX Onboarding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full flex justify-center items-center">
        <div className="h-screen flex flex-col justify-center items-center border-teal-600">
          <p className="">{JSON.stringify(user, null, 2)}</p>
          <div>
            <button
              className="border-4 p-2 bg-blue-600 rounded-lg"
              onClick={linkSetup}
            >
              Link Wallet
            </button>
            <button
              className="border-4 p-2 bg-blue-600 rounded-lg"
              onClick={getUserProjects}
            >
              Get Projects
            </button>
            <button
              className="border-4 p-2 bg-blue-600 rounded-lg"
              onClick={getUserAssets}
            >
              Get Assets
            </button>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
